// Generated by CoffeeScript 1.3.3
(function() {
  var Game, MAX_TIME;

  MAX_TIME = 300;

  Game = (function() {

    function Game() {
      this.field = new Field;
      this.score = 0;
      this.inProgress = false;
      this.time = MAX_TIME;
    }

    Game.prototype.updateScore = function(increment) {
      this.score += increment;
      return $('score').text = this.score;
    };

    Game.prototype.runClock = function() {
      if (this.inProgress) {
        this.time--;
        $('clock').text = this.time / 60 + ":" + this.time % 60;
        return setTimeout(runClock, 1000);
      }
    };

    Game.prototype.startClock = function() {
      if (!this.inProgress) {
        this.inProgress = true;
        return setTimeout(runClock, 1000);
      }
    };

    Game.prototype.stopClock = function() {
      return this.inProgress = false;
    };

    return Game;

  })();

}).call(this);
