// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  $(document).ready(function() {
    window.game = new Game();
    $("#start").click(function() {
      return window.game.startClock;
    });
    return $("#square").click(sqClick);
  });

}).call(this);
