// Generated by CoffeeScript 1.3.3
(function() {
  var CHECKED, MARKED, MINE, NOT_CHECKED, NOT_MINE, QED, Square, UNKNOWN;

  NOT_MINE = 0;

  MINE = 1;

  UNKNOWN = 2;

  NOT_CHECKED = 0;

  CHECKED = 1;

  MARKED = 2;

  QED = 3;

  Square = (function() {

    function Square(isMine, isChecked, index, number) {
      this.isMine = isMine != null ? isMine : NOT_MINE;
      this.isChecked = isChecked != null ? isChecked : NOT_CHECKED;
      this.index = index;
      this.number = number != null ? number : -1;
    }

    Square.prototype.getClass = function() {
      switch (this.isChecked) {
        case NOT_CHECKED:
          return "";
        case MARKED:
          return "marked";
        case QED:
          return "qed";
        case CHECKED:
          if (this.isMine === MINE) {
            if (this.number <= 0) {
              return "boom";
            } else {
              return "boom" + this.mines;
            }
          } else {
            if (this.number <= 0) {
              return "clear";
            } else {
              return "clear" + this.mines;
            }
          }
      }
    };

    return Square;

  })();

}).call(this);
