// Generated by CoffeeScript 1.3.3
(function() {
  var LOSS_VAL, WIN_VAL, sqClick, sqLeftClick, sqRightClick, updateBoard;

  WIN_VAL = 10;

  LOSS_VAL = -10;

  sqClick = function(target) {
    switch (target.which) {
      case "1":
        return sqLeftClick(target);
      case "3":
        return sqRightClick(target);
      default:
        return true;
    }
  };

  sqLeftClick = function(target) {
    var val, _i, _len;
    window.game.field.clickSquare(target.id, vals, !gInProgress);
    window.game.startClock();
    for (_i = 0, _len = vals.length; _i < _len; _i++) {
      val = vals[_i];
      switch (val.result) {
        case "boom":
          updateBoard(target, "mine", "lose");
          break;
        case "money":
          updateBoard(target, val.newClass, "win");
      }
    }
    return true;
  };

  sqRightClick = function(target) {
    var val;
    val = window.game.field.markSquare(target.id);
    updateBoard(target, val.newClass, "mark");
    return true;
  };

  updateBoard = function(target, newClass, status) {
    if (!target.hasClass(newClass)) {
      target.removeClass();
      target.addClass("square");
      target.addClass(newClass);
    }
    switch (status) {
      case "win":
        window.game.updateScore(WIN_VAL);
        break;
      case "lose":
        window.game.updateScore(LOSS_VAL);
    }
    return true;
  };

}).call(this);
